version: '3.8'

services:
  arb_read:
    build: ./arb_read
    ports:
      - "1337:1337"

  student_env:
    build: ./student_env
    ports:
      - "22:22"
      
  webpage:
    build: ./webpage
    ports:
      - "8080:8080"

